kind: pipeline
name: "Publicação de Site hugo Nordsh"

trigger:
  branch:
    - develop
    - main
  event:
    - push

steps:
  - name: build
    image: klakegg/hugo:alpine
    environment:
      KEY:
        from_secret: KEY
    commands:
      - apk --no-cache update
      - apk add git
      - mkdir ~/.ssh/
      - echo $KEY > ~/.ssh/id_rsa
      - chmod 400 ~/.ssh/id_rsa*
      - echo StrictHostKeyChecking no >> ~/.ssh/config
      - chmod 400 ~/.ssh/config
      - git clone  git@github.com:nordsh/nordsh.github.io.git gh-site
      - hugo