kind: pipeline
name: "Publicação de Site hugo Nordsh"

trigger:
  branch:
    - develop
    - main
  event:
    - push

steps:
  - name: build
    image: plugins/hugo
    settings:
      hugo_version: 0.110.0
      validate: true
      config: app/config.toml
      content: app

  - name: publish
    image: gvacaliuc/drone-gh-pages
    settings:
      pages_directory: public
      upstream_name: https://github.com/nordsh/nordsh.github.io.git
      target_branch: main
      force_push: true
      username:
        from_secret: GH_USER
      password:
        from_secret: GH_PASS