kind: pipeline
name: "Publicação de Site hugo Nordsh"

trigger:
  branch:
    - develop
    - main
  event:
    - push

steps:
  - name: build
    image: klakegg/hugo:alpine
    commands:
      - apk --no-cache update
      - apk add git openssh-client
      - eval $(ssh-agent -s)
      - mkdir ~/.ssh/
      - ssh-add <(echo "$KEY")
      - echo "$KEY" > ~/.ssh/id_ed25519.pub
      - chmod 0600 ~/.ssh/id_ed25519.pub*
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      - git config --global user.name "Rosthan Silva"
      - git config --global user.email "rosthanlinux@gmail.com"
      - git clone  git@github.com:nordsh/nordsh.github.io.git
      - ls nordsh.github.io