kind: pipeline
name: "Publicação de Site hugo Nordsh"

trigger:
  branch:
    - develop
    - main
  event:
    - push

steps:
  - name: build
    image: klakegg/hugo:alpine
    commands:
      - apk --no-cache update
      - apk add git
      - git config --global user.name "Rosthan Silva"
      - git config --global user.email "rosthanlinux@gmail.com"
      
      - git clone  https://rosthansilva:$GIT_TOKEN@git@github.com:nordsh/nordsh.github.io.git
      - ls nordsh.github.io