kind: pipeline
name: "Publicação de Site hugo Nordsh"

trigger:
  branch:
    - develop
    - main
  event:
    - push

steps:
  - name: build
    image: klakegg/hugo:alpine
    environment:
      KEY:
        from_secret: KEY
    commands:
      - apk --no-cache update
      - apk add git openssh-client 
      - mkdir ~/.ssh/
      - echo $KEY > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa*
      - echo '    StrictHostKeyChecking no' >> ~/.ssh/config
      - echo "Host *" >> ~/.ssh/config
      - cat ~/.ssh/config
      - chmod 400 ~/.ssh/config
      - GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone  git@github.com:nordsh/nordsh.github.io.git gh-site
      - hugo