---
- name: git module demo
  hosts: all
  vars:
    repo: "git@github.com:nordsh/nordsh.github.io.git"
    dest: "/tmp/nordsh.github.io"
    sshkey: "~/.ssh/id_ed25519.pub"
  tasks:
    - name: ensure git pkg installed
      ansible.builtin.yum:
        name: git
        state: present
        update_cache: true
      become: true

    - name: checkout git repo
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: "{{ dest }}"
        key_file: "{{ sshkey }}"
    
